[package]
name = "noeio-common"
version = "0.3.0"
edition = "2024"

[dependencies]
bytes = { workspace = true }
hostname = { workspace = true }
smoltcp = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }
noeio-proto = { workspace = true, features = ["common"] }
prost = { workspace = true }

[target.'cfg(windows)'.dependencies]
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true, features = ["default"] }
